services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: the_shopper
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      shopper-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-shopper
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


  networks:
    shopper-demo:
      driver: bridge


  volume:
    postgres:
      driver: local